module.exports = [
  {
    id: "978-4-480-06815-6",
    title: "老人喰い-高齢者を狙う詐欺の正体",
    type: "book",
    authors: ["鈴木大介"],
    publisher: "筑摩書房",
    year: 2015,
    category: "犯罪",
    status: "read",
    isbn: "978-4-480-06815-6",
    note: "FANGの犯罪スキームを考案するために参照。",
    relatedPersons: ["延金英一", "篠原堅", "戸次信長"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-166-60961-1",
    title: "詐欺の帝王",
    type: "book",
    authors: ["溝口敦"],
    publisher: "文藝春秋",
    year: 2014,
    category: "犯罪",
    status: "read",
    isbn: "978-4-166-60961-1",
    note: "FANGと取引を行う特殊詐欺集団の内情を理解するために参照。",
    relatedPersons: ["延金英一", "葛城正親"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-106-10434-3",
    title: "暴力団",
    type: "book",
    authors: ["溝口敦"],
    publisher: "新潮社",
    year: 2011,
    category: "犯罪",
    status: "read",
    isbn: "978-4-106-10434-3",
    note: "犯罪組織であるFANGの姿を考察するために参照。",
    relatedPersons: ["延金英一", "葛城正親", "風間竜也", "篠原堅"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-10-610492-3",
    title: "続・暴力団",
    type: "book",
    authors: ["溝口敦"],
    publisher: "新潮社",
    year: 2012,
    category: "犯罪",
    status: "read",
    isbn: "978-4-10-610492-3",
    note: "犯罪組織であるFANGの姿を考察するために参照。",
    relatedPersons: ["延金英一", "葛城正親", "風間竜也", "篠原堅"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-040-82093-4",
    title: "山口組 顧問弁護士",
    type: "book",
    authors: ["山之内幸夫"],
    publisher: "KADOKAWA",
    year: 2016,
    category: "犯罪",
    status: "to-read",
    isbn: "978-4-040-82093-4",
    note: "犯罪組織であるFANGの姿を考察するために参照。",
    relatedPersons: ["延金英一", "葛城正親"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-334-03918-9",
    title: "闇経済の怪物たち～グレービジネスでボロ儲けする人々～",
    type: "book",
    authors: ["溝口敦"],
    publisher: "光文社",
    year: 2016,
    category: "犯罪",
    status: "read",
    isbn: "978-4-334-03918-9",
    note: "犯罪組織FANGが法の目をかいくぐる手段を検討するために参照。",
    relatedPersons: ["延金英一", "葛城正親"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-344-98622-0",
    title: "薬物売人",
    type: "book",
    authors: ["倉垣弘志"],
    publisher: "幻冬舎",
    year: 2021,
    category: "犯罪",
    status: "read",
    isbn: "978-4-344-98622-0",
    note: "FANGが犯す犯罪である薬物売買の実態を知るために参照。",
    relatedPersons: ["延金英一", "戸次信長"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-062-56327-7",
    title: "山口組四代目 荒らぶる獅子",
    type: "book",
    authors: ["溝口敦"],
    publisher: "講談社",
    year: 1999,
    category: "犯罪",
    status: "to-read",
    isbn: "978-4-062-56327-7",
    note: "犯罪組織であるFANGの姿を考察するために参照。",
    relatedPersons: ["延金英一", "葛城正親"],
    relatedPhases: ["PROJECTION"]
  },
{
    id: "978-4-422-11571-9",
    title: "児童養護施設児の日常とこころ：施設内心理療法家の観点から",
    type: "book",
    authors: ["森田喜治"],
    publisher: "創元社",
    year: 2013,
    category: "児童虐待",
    status: "to-read",
    isbn: "978-4-422-11571-9",
    note: "児童養護施設で育つ篠原堅と本田千和の生活を想像するために参照。",
    relatedPersons: ["篠原堅"],
    relatedPhases: ["BLOOD","PROJECTION"]
  },
{
    id: "978-4-422-11380-7",
    title: "児童養護施設と被虐待児-施設内心理療法家からの提言",
    type: "book",
    authors: ["森田喜治"],
    publisher: "創元社",
    year: 2006,
    category: "児童虐待",
    status: "to-read",
    isbn: "978-4-422-11380-7",
    note: "被虐待児である篠原堅の心理を理解するために参照。",
    relatedPersons: ["篠原堅"],
    relatedPhases: ["BLOOD","PROJECTION"]
  }
];